name: Release
on: 
  push: 
    branches: 
      - main
  workflow_dispatch:
env: 
  VERSION: '13.0.1' 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Remove unwanted files
        run: |
          rm -rf my_workspaces/.my_workspaces
          rm -rf README.md
          rm -rf README_EN.md
          rm -rf .git
          rm -rf .github
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with: 
          tag_name: ${{ env.VERSION }}
          release_name: UY-Scuti ${{ env.VERSION }}
          draft: false
          prerelease: false
          body: |
            ## 更新内容

            1. 分区打包已支持多选，现在无论是提取分区，还是打包分区，都可以多选了。  
            2. super 打包移除固定值，现在总是动态计算或是保持原大小。  
            3. 全局 Deodex 回来了。  
            4. 快速替换目录调整到根目录下，这样修改更加快速。  
            5. 提示：ONEUI 特性添加已经移除，现在变成更直观的修改选项。  
            6. ColorOS 已添加较多精简列表应用。  
            7. 教程更新。

            ## Release Notes

            1. Partition packaging now supports multi-selection; whether extracting or packaging partitions, multiple selections are supported.  
            2. Fixed values removed from super packaging; it now always dynamically calculates or retains the original size.  
            3. Global Deodex functionality has been restored.  
            4. The quick replace directory has been moved to the root directory for faster modifications.  
            5. Note: ONEUI feature additions have been removed and replaced with more intuitive modification options.  
            6. Many streamlined list apps have been added to ColorOS.  
            7. Tutorial updated.
      - name: Archive project
        run: zip -r UY-Sct_${{ env.VERSION }}.zip .
        
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./UY-Sct_${{ env.VERSION }}.zip
          asset_name: UY-Sct_${{ env.VERSION }}.zip
          asset_content_type: application/zip

